= BPI-CM6 Introduction

Banana Pi BPI-CM6 is a industrial grade RISC-V Core board, it design with SpacemiT K1 8 core RISC-V chip, CPU integrates 2.0 TOPs AI computing power. 2/4/8/16G DDR and 8/16/32/128G eMMC.,Designed with Board to Board connectors for enhanced stability same as Raspberry Pi CM4.

TIP: SpacemiT K1 RISC-V link:/en/BPI-F3/BananaPi_BPI-F3[Banana Pi BPI-F3] AI SBC design +
SpacemiT K1 RISC-V link:/en/BPI-CM6/BananaPi_BPI-CM6[Banana Pi BPI-CM6] AI Computer module design

== About SpacemiT K1 8 core RISC-V chip

SpacemiT K1 is an octa-core 64-bit RISC-V AI CPU. Base on RISC-V open instruction set architecture,we are committed to create more energy efficient and more commonly used AI processor platform,promote global open source and open ecological computing power construction.

SpacemiT K1 is mainly used for single board computer,network storage,cloud computer,smart robort,industrial control,edge computer,etc.

TIP: link:/en/BPI-F3/SpacemiT_K1[SpacemiT K1 8 core RISC-V chip Brief] +
link:/en/BPI-F3/SpacemiT_K1_datasheet[SpacemiT K1 8 core RISC-V chip datasheet] +
link:https://developer.spacemit.com/[SpacemiT official development center]

== Key Features

== Application direction

* NAS
* Laptop
* Intelligent robotics
* Industrial control
* AI edge computing
* Automation

== Getting Start

= Hardware

== Hardware Interface

== Hardware Spec

== BPI-CM6 Photo

== BPI-CM6 Block Diagram

== BPI-CM6 core board pin definitions

= BPI-CM5 Pro IO board

== IO board Hardware Specifications

== Hardware Interfaces

== GPIO define

= Development

== Source code

=== Bianbu linux 

TIP: Bianbu source code： https://gitee.com/bianbu-linux/linux-6.1 

TIP: Bianbu uboot code: https://gitee.com/bianbu-linux/uboot-2022.10

TIP: Bianbu OpenSBI code: https://gitee.com/bianbu-linux/opensbi

* link:https://bianbu-linux.spacemit.com/en/[Bianbu linux Introduction and development manual]

=== OpenWrt

TIP: OpenWrt source code: https://archive.spacemit.com/openwrt/releases/23.05.2/

=== Linux BSP Source Code

TIP: pi-opensbi: https://github.com/BPI-SINOVOIP/pi-opensbi/tree/v1.3-k1

TIP: u-boot: https://github.com/BPI-SINOVOIP/pi-u-boot/tree/v2022.10-k1

TIP: kernel: https://github.com/BPI-SINOVOIP/pi-linux/tree/linux-6.1.15-k1

TIP: Armbian: https://github.com/BPI-SINOVOIP/armbian-build/tree/v24.04.30

== RISC-V IME set Specification 

SpacemiT K1 8 core RISC-V chip (Banana Pi BPI-F3) RISC-V IME set Specification public on github

TIP: https://github.com/space-mit/riscv-ime-extension-spec

== Resources


= System Image

== Tools

TIP: Windows PC: https://download.banana-pi.dev/d/ca025d76afd448aabc63/files/?p=%2FTools%2Fimage_download_tools%2Ftitantools_for_windows-1.0.35-beta.zip

TIP: Linux PC: https://download.banana-pi.dev/d/ca025d76afd448aabc63/files/?p=%2FTools%2Fimage_download_tools%2Ftitantools_for_linux-1.0.35-beta.zip

== All image download:


= FAQ



= Easy to buy
