= BPI-CM6 Introduction

Banana Pi BPI-CM6 is a industrial grade RISC-V Core board, it design with SpacemiT K1 8 core RISC-V chip, CPU integrates 2.0 TOPs AI computing power. 2/4/8/16G DDR and 8/16/32/128G eMMC.,Designed with Board to Board connectors for enhanced stability same as Raspberry Pi CM4.

== About SpacemiT K1 8 core RISC-V chip

SpacemiT K1 is an octa-core 64-bit RISC-V AI CPU. Base on RISC-V open instruction set architecture,we are committed to create more energy efficient and more commonly used AI processor platform,promote global open source and open ecological computing power construction.

SpacemiT K1 is mainly used for single board computer,network storage,cloud computer,smart robort,industrial control,edge computer,etc.

TIP: link:/en/BPI-F3/SpacemiT_K1[SpacemiT K1 8 core RISC-V chip Brief] +
link:/en/BPI-F3/SpacemiT_K1_datasheet[SpacemiT K1 8 core RISC-V chip datasheet] +
link:https://developer.spacemit.com/[SpacemiT official development center]

== Key Features

== Application direction

* NAS
* Laptop
* Intelligent robotics
* Industrial control
* AI edge computing
* Automation
