= Allwinner Tina-IoT 操作系统 BPI-M2 Ultra

== 关于蒂娜物联网 Linux

尊敬的用户 BPI-M2 Ultra R40 蒂娜 Linux V1.0已经公开，快来试试

蒂娜 Linux 开发者 Allwinner TinaTEAM，它基于 OpenWrt,构建一个嵌入式 Linux 发行版，本次发布的目的是提供快速学习开发简单方便量产的方式 Linux 交钥匙解决方案。

R40蒂娜的发布 Linux 是基于 BPI-M2 Ultra 参考硬件，即源码下载直接支持香蕉派 BPI-M2 Ultra.

R40 蒂娜 Linux V1.0版本基于 Linux-3.10和蒂娜 Linux V2.1，支持很多好玩又实用的支持功能：

1.支持smartlink（超声波、airkiss、cooee）

2.支持DLNA、QPlay音频传输及控制协议

太多了，就不一一讲了，支持所有硬件模块 BPI-M2 Ultra

== 如何使用R40蒂娜 Linux

玩Tina需要64位 Linux PC，我们推荐使用 Ubuntu 12.04或14.04 64位版本，使用以下命令安装，安装编译环境依赖：


sudo apt-get install build-essential subversion git-core libncurses5-dev zlib1g-dev gawk flex quilt libssl-dev xsltproc libxml-parser-perl mercurial bzr ecj cvs unzip


详细的你可以参考 link:https://wiki.openwrt.org/doc/howto/buildroot.exigence[OpenWrt维基百科]

下载源代码

使用repo工具下载该代码，工具下载方法如下：

```sh
curl https://raw.githubusercontent.com/tinalinux/repo/stable/repo > ~/bin/repo $ chmod +x ~/bin/repo
```

然后在环境变量中添加“repo”，最好放下面这句话。里面的.bashrc


```sh
export PATH=~/binPATH
```

下载repo，接下来下载Tina的源码，如下：

```sh
repo init -u https://github.com/tinalinux/manifest -b r40-v1.y -m r40/v1.y.xml
repo sync
repo start r40-v1.y --all
```

下载源代码后，在编译好的Tina目录下执行以下命令：

```sh
source build/envsetup.sh
lunch azalea_m2ultra-tina
make -j4
pack [-d]
```

蒂娜 SDK 每次编译前都需要执行“source”和“lunch”commond，然后再执行其他操作。

pack命令有一个“-d”参数，该参数的作用是：不加-d使用默认的uart0作为串口输出，加-d使用TF卡口IO口组作为uart0

== 烧录镜像

Tina镜像打包有15M左右，支持直接烧录到 eMMC 闪光 BPI-M2 Ultra.

烧制方法如下：

如果你使用 Linux 系统，直接使用LiveSuit进行刷机。使用方法如下：

. LiveSuit 我们把它放在 tina 处 SDK tools/aw\_工具目录

. unzip LiveSuit 64bit version，run./LiveSuit.sh

. LiveSuit 将安装在 ~/Bin dir，使用 dpkg -i install aw driver,driver也在 ~/Bin 目录。

. 运行LiveSuit，选择tina图片

. 按住 BPI-M2 Ultra uboot键，插入 usb ，就可以开始刻录镜像了

如果使用 Windows 系统请使用烧录工具：phoenixsuit

我们把它放在 tools/aw\_工具目录

== 如何配置蒂娜

Tina固件配置，常用的命令有两个：“make menuconfig”和“make kernel”\_菜单配置”。

这两个命令必须在“source”和“lunch”commond运行完成后执行，

make menuconfig : Which software is used to configure the system use

make kernel\_menuconfig:Used to configure the kernel options.

TinaLinux 源代码 github: https://github.com/tinalinux/