= BPI-RT2 Introduct
BPI-RT2 Router use Realtek RTL8198D design. It is a high performance wireless router for small and micro businesses, homes and other networking environments.

BPI-RT2 Router dual-band wireless router, 2.4G 2T2R, 5G 2T2R coexist at the same time. The use of four omni-directional high-gain antennas, with strong signal penetration and wider coverage, which makes the already strong signal more powerful, data transmission is also smoother. MU-MIMO multi-device transceiver technology has low latency and multiple devices are stably connected simultaneously, thus ensuring a good experience for multiple devices.


== Realtek RTL8189D
The Realtek RTL8198D is a highly integrated system-on-chip (SoC) designed for high-performance networking devices. It integrates a dual-core CPU, a hardware switching engine, multi-port Gigabit Ethernet PHY transceivers, and comprehensive network protocol processing acceleration functions, making it an ideal core solution for building enterprise-grade gateways, smart routers, and network switching equipment.
The RTL8198D integrates four Gigabit Ethernet physical layer transceivers for 10Base-T, 100Base-TX, and 1000Base-TX, and and 1 USB 3.0 port.