= Overview

Banana Pi BPI-M77 is powered by Rockchip's latest flagship RK3588,octa-core 64-bit processor, with a max frequency of 2.4GHz, a 6 TOPS NPU, and up to 32GB of RAM.

== Key Features:

* 8K video encoding/decoding support
* Abundant interfaces support
* Dual 2.5G Ethernet support
* WiFi 6 support
* BT 5 support
* Multiple video outputs support
* Multiple operating systems support

Generally, BPI-M7 is applied for various applications,such as, ARM PCs, edge computing, cloud servers, AI, cloud computing, virtual/augmented reality, blockchain, smart NVRs and more.

TIP: With the powerful ecosystem and variety of extension modules, ArmSoM can help users easily go from ideas to prototype to mass production, making it an ideal creative platform for makers, dreamers and hobbyists.

== Key Parameter

* SoC: Rockchip RK3588
* CPU: 4x Cortex-A76 @ 2.4GHz + 4x Cortex-A55 @ 1.8GHz, 8nm
* GPU: ARM Mali-G610 MP4
* NPU: Up to 6 TOPS (INT8), supports INT4/INT8/INT16 mixed computing
* VPU/Codec:
** Hardware Decode: 8K@60fps H.265/VP9/AVS2, 8K@30fps H.264 AVC/MVC, 4K@60fps AV1, 1080P@60fps MPEG-2/-1/VC-1/VP8
** Hardware Encode: 8K@30fps H.265 / H.264
* RAM: 8GB/16GB/32GB (max 32GB) 64bit LPDDR4/LPDDR4x, default 8GB LPDDR4x
* Storage: 64GB/128GB eMMC, default 64GB eMMC
* Operating Voltage: Wide input voltage, 5V to 20V (±5% tolerance)
* Operating temperature: 0°C ~ 70°C
* OS:
** Official: Android 12.0, Debian 11, Buildroot
** 3rd party: Armbian, Ubuntu 20.04, Ubuntu 22.04, Kylin OS
* PCB: 12-layer
* Weight: 200g 
* Size: 92mm × 62mm