== BPI-R4 Pro Introduction

Banana Pi BPI-R4 Pro Router board with MediaTek MT7988A(Filogic 880) quad-core ARM Corex-A73 design ,4GB/8GB DDR4 RAM,8GB eMMC,128MB SPI-NAND flash onboard.it is a update version for BPI-R4.


TIP: MediaTek MT7988 (Filogic 880) design: link:/en/BPI-R4_Pro/BananaPi_BPI-R4_Pro[Banana Pi BPI-R4 Pro] Router development board +
MediaTek MT7988 (Filogic 880) design: link:/en/BPI-R4/BananaPi_BPI-R4[Banana Pi BPI-R4] Router development board + 
MediaTek MT7986(Filogic 830) design: link:/en/BPI-R3_Mini/BananaPi_BPI-R3_Mini[Banana Pi BPI-R3 Mini] Mini size Router development board +
MediaTek MT7986(Filogic 830) design: link:/en/BPI-R3/BananaPi_BPI-R3[Banana Pi BPI-R3] Router development board 


== MediaTek MT7988(Filogic 880)

Mediatek Filogic 880. the 36Gbps Wi-Fi 7 access point/router/gateway platform delivers the fastest and most reliable connection experience

The MediaTek MT7988A is a world-Leading network processing platform for high-performance and reliable networking experiences,both in wired and wireless applications. The MT7988A comprises a rich connection interface sets include 4 Gigabit Ethernet ports. 2 US下GMII interfaces. 4 PCIe Interfaces,and 2 USB 3.2 en1 Ports

the MT7988A further enables seamless Wi-Fi 7 tri-band,2.4 GHz.5 GHz and 6 GHz,connectivity,with its Wi-Fi 7 companion chip that features 320-MHz bandwidth,4096-QAM ,MLO,MRU,and AFC.

To answer the need of fast-evolving tunneling applications,the MT7988A comes with MediaTek Tunnel offload processor System(TOPS),which facilitates the processing of a wide range of tunneling protocols.The MT7988A optimizes networking performance with exquistitely tuned ISA of MediaTek TOPS,and is dedicated to lifting networking offloading performance to premium level.

== Key Features

== Application direction

- Internet service Router
- Wifi 7 Wireless Router
- 4G/5G Wireless Router
- Wireless Repeater
- Home security Gateway
- Home Automation
- Nas device
- Network and communication applications

== Getting Start

TIP: link:/en/BPI-R4_Pro/GettingStarted_BPI-R4_Pro[Getting Started BPI-R4 Pro]

TIP: link:/en/BPI-R4/GettingStarted_BPI-R4[Getting Started BPI-R4]

TIP: link:https://www.fw-web.de/dokuwiki/doku.php?id=en:bpi-r4:start#linux[Frank wiki for BPI-R4]