= Introduction

Banana Pi BPI-R4 Router board with MediaTek MT7988A (Filogic 880) quad-core ARM Corex-A73 design ,4GB DDR4 RAM,8GB eMMC,128MB SPI-NAND flash onboard, also have 2x 10Gbe SFP, 4x Gbe network port,with USB3.2 port,M.2 support 4G/5G/NVME SSD.2x miniPCIe slots with PCIe3.0 2lane interface for Wi-Fi 7 NIC (Network Interface Card). It is a very high performance open source router development board.

TIP: More Infomation: link:https://docs.banana-pi.org/en/BPI-R4_Pro/BananaPi_BPI-R4_Pro[Banana Pi BPI-R4Pro]

= Development
== Prepare

* Prepare 8G/above TF card, USB TypeC cable, Ubuntu System
* 12V/5A power adapter (without any peripherals and network cable inset, the power consumption of BPI-R4Pro Main Board is about 10W,so 12V/2A will work.but you need to determine whether you need a higher power power adapter according to your own accessory usage)
* Using your USB-Serial cable(3.3V TTL,Baud=115200) Connect to debug console on BPI-R4 +
G=GND;  RX=BPI-R4 input;  TX=BPI-R4 output0
* link:https://docs.banana-pi.org/en/BPI-R4/BananaPi_BPI-R4#_system_image[Download the image] to be burned
* Default IP address for LAN port: 192.168.1.1
* User name/password: pi/bananapi ,root/bananapi. +
Or the user is root without a password.
* WIFI: AP_MTK_MT7990_2G/AP_MTK_MT7990_5G/AP_MTK_MT7990_6G