= Introduction

Banana Pi BPI-P2 Zero is an ultra compact single board computer measures only 65mm*52.5mm. It uses quad-core Cortex A7 allwinner H2+ processor(Option : H3 and H5), with 512MB RAM memory.8G eMMC flash,100M LAN,add PoE function support , It's ideal for light-weight systems with some space-limited applications. Like other members of Banana Pi, it supports both linux and android operating system.

TIP: More Infomation: link:/en/BPI-P2_Zero/BananaPi_BPI-P2_Zero[Banana Pi BPI-P2 Zero]

== specifications

- CPU: Allwinner H2+, Quad-core Cortex-A7
- 512MB DDR 3 SDRAM
- WiFi (AP6212) & Bluetooth onboard
- Mini HDMI
- 40 PIN GPIO, It includes UART, SPI, I2C, IO etc
- 100M LAN
- IEEE 802.3af PoE standard PoE module support
- 8G eMMC flash onboard

= Development
== Prepare

xxxxxx

xxxxxx

xxxxxx

== Android
=== Prepare

. xxx
. xxx
. xxx
. xxx

=== Install Image with xxx

. xxx
. xxx
. xxx
. xxx

=== Install Image with xxx

. xxx
. xxx
. xxx
. xxx

== Linux
=== Prepare

. xxx
. xxx
. xxx
. xxx

=== Install Image with xxx

. xxx
. xxx
. xxx
. xxx

=== Install Image with xxx

. xxx
. xxx
. xxx
. xxx
