= BPI-R2 Mini Introduction



TIP: MediaTek MT7988 (Filogic 880) design: link:/en/BPI-R4_Pro/BananaPi_BPI-R4_Pro[Banana Pi BPI-R4 Pro] Router development board +
MediaTek MT7988 (Filogic 880) design: link:/en/BPI-R4/BananaPi_BPI-R4[Banana Pi BPI-R4] Router development board +
MediaTek MT7987 (Filogic 860) design: link:/en/BPI-R4_Lite/BananaPi_BPI-R4_Lite[Banana Pi BPI-R4 Lite]  Router board +
MediaTek MT7987 (Filogic 860) design: link:/en/BPI-R4_Mini/BananaPi_BPI-R4_Mini[Banana Pi BPI-R4 Mini]  Wifi7 Router board +
MediaTek MT7986(Filogic 830) design: link:/en/BPI-R3_Mini/BananaPi_BPI-R3_Mini[Banana Pi BPI-R3 Mini] Mini size Router development board +
MediaTek MT7986(Filogic 830) design: link:/en/BPI-R3/BananaPi_BPI-R3[Banana Pi BPI-R3] Router development board 

== MediaTek MT7981


== Key Features



== Application direction



== Getting Start

TIP: link:/en/BPI-R2_Mini/GettingStarted_BPI-R2_Mini[GettingStarted BPI-R2 Mini]



= Hardware
== Hardware Interface

== BPI-R1 Mini Photo

link:/en/BPI-R2_Mini/BPIR2MiniProductphotogallery[BPI-R2 Mini Product photo gallery]

== Hardware Spec



= Accessories

= Development
== Source Code

== Resources


= System Image

= Easy to buy