= 简介

香蕉派 R2 是一款基于路由器的开发板，可以在多种开源操作系统上运行，包括 OpenWrt, Android和巴纳尼安。它具有 4 个千兆 LAN 端口、1 个千兆 WAN 和 300Mbs 无线 N 功能。 

TIP: 更多信息： link:/en/BPI-R2/BananaPi_BPI-R2[香蕉派 BPI-R2]

== 主要特性
- MediaTek MT7623N，四核 ARM Cortex-A7
- 马里450 MP4 GPU
- 2G DDR3内存
- 1x 迷你 PCIE 接口
- 2 个 SATA 接口
- 4 个千兆 LAN 1 个千兆 WAN

= 硬件
== BPI-R2 SATA接口
BPI-R2 支持2个SATA接口和板载电源端口。



您可以使用SATA线连接您的硬盘 BPI-R2.

测试三星 SSD 磁盘， Read/Write 性能如下：

从磁盘读取： 230MB/s 
```sh
dd if=/dev/sda of=/dev/zero bs=1M count=10240\
```

写入磁盘： 192MB/s 
```sh
dd if=/dev/zero of=/dev/sda bs=1M count=1024 oflag=direct\
```

WARNING: 注意：如果您使用3.5大硬盘，可能需要外接电源供电。板载电源可能无法支持足够的电流
= 开发
让我们开始开发BPI-R2，看到奇妙的事情发生。

== 准备开发
* 准备 16G/above TF卡、 USB-串行接口， Ubuntu 系统
* 使用您的 USB-串行 (3.3V，波特率：115200)  连接 R2 上的调试控制台
* LAN口默认IP地址：192.168.1.1
* 用户 name/password: pi/bananapi ,root/bananapi. +
或者用户是root，没有密码。



* BananaPi R2-调试-UART: http://www.fw-web.de/dokuwiki/doku.php?id=en:bpi-r2:debug-uart

== 在 R2 上加载您的第一张图像
. 您可以从我们的论坛下载最新图片
+
这是示例镜像链接： http://forum.banana-pi.org/t/bpi-r2-new-image-release-ubuntu-16-04-v1-3-2018-3-30/5293
 
. 安装 bpi-tools 在你的 Ubuntu。如果您无法访问此网址或有任何其他问题，请访问 bpi-tools 存储库并手动安装此工具。
+
```sh
apt-get install pv
curl -sL https://github.com/BPI-SINOVOIP/bpi-tools/raw/master/bpi-tools | sudo -E bash
```
 
. 下载镜像后，将TF卡插入电脑Ubuntu
+
```sh
bpi-copy xxx.img /dev/sdx
```
. 步骤3后，您可以将TF卡插入R2，然后按住电源按钮约10秒以设置R2

== 更新您的 Ubuntu 在 SD 卡上
. 从以下位置克隆 Bsp 项目 Github,执行
+
```sh
git clone git@github.com:BPI-SINOVOIP/BPI-R2-bsp.git
``` 
. 执行
+
```sh
./build.sh
```
构建您自己的 uboot 和内核。
+
R2 构建 sh.png
 
. 构建完成后，执行
+
```sh
cd SD
```
插入你的 Ubuntu PC 中的 TF 卡。 
 
. 执行
+
```sh
bpi-update -c bpi-r2.conf -d /dev/sdX
```
将编译好的内核更新到你的TF卡上。

== Ubuntu 开 Emmc
如果你想安装 Ubuntu 上 EMMC，请按照下列步骤操作：

* 将镜像刻录到SD卡，并用SD卡设置R64。
* 复制名称包含“的镜像**xxx-emmc-xxx**”到U盘。
* mount U disk to R64, then use bpi-copy to burn image to Emmc. 
```sh
   bpi-copy  <XXX.img.zip> 
```
* XXX.img.zip 是 ubuntu 我们可以从中得到它 http://www.banana-pi.org/r2-download.html 
 * 关闭电源
 * 取出 SD 卡并开机

== OpenWrt 在标清& Emmc 步骤
--
. 克隆 OpenWrt 项目来自 Github.
+
```sh
git clone https://github.com/garywangcn/bpi-r2_lede.git
```
 
. 你需要安装 gcc、binutils、bzip2、flex、 python、 perl、make、find、grep、diff、unzip、gawk、getopt、subversion、libz-dev 和 libc 标头。
 
. 运行“./scripts/feeds update -a" 来获取所有最新的包定义 feeds.conf / feeds.conf.default分别和“./scripts/feeds install -a" 将它们的符号链接安装到 package/feeds/.
 
. 使用“make menuconfig”来配置您的图像。
 * 选择“目标系统”配置为“MediaTek 雷凌ARM”
 * 选择“Boot Loaders”配置为“u-boot-bpi_r2"
 
. 执行“make -j1 V=s”来构建你自己的 OpenWrt 镜像。
 
. 构建完成后，我们有两种方式安装镜像。
..插入你的TF卡 Ubuntu 电脑，然后输入“build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-mediatek_32/", 
     you will find two images:
     * mtk-bpi-r2-EMMC.img
     * mtk-bpi-r2-SD.img
..将镜像写入TF卡，执行“dd if=mtk-bpi-r2-SD.img 的=/dev/sdX"
 
..如果你想安装镜像 EMMC，我们需要另一个运行在SD卡上的系统来编程 EMMC 镜像到 EMMC，请按照以下步骤进行：
     * 复制 EMMC 来自 SD 卡的映像到正在运行的系统
     * 节目 EMMC 镜像到用户数据区 EMMC: dd 如果=mtk-bpi-r2-EMMC.img 的=/dev/mmcblk0 (假设 /dev/mmcblk0 是为了 EMMC)
     * 解锁 EMMC boot0 块：echo 0 > /sys/block/mmcblk0boot0/force_ro
     * 将预加载器编程为 EMMC boot0 块：dd if=mtk-bpi-r2-EMMC.img 的=/dev/mmcblk0boot0 废话=100万个=1
     * 更改分区配置 EMMC 为48h：重启运行SD的系统，进入U-boot命令行，运行命令 emmc pconf 48 (对于此步骤，我们可以使用 mmc-utils 更改用户空间中的分区配置，请参阅中的更多信息 BPI-R2 OpenWrt(发光二极体) 源代码 : 2018-04-11)
     * 断电，取出SD卡，然后给R2板上电
 
. 此步骤用于升级，如果构建后不想安装映像，可以使用运行时升级。
 * 复制“bin/targets/mediatek/32/lede-mediatek-32-bananapi,bpi-r2-sysupgrade.tar” 到正在运行的 R2 板 OpenWrt 系统(无论在哪里(标清或 EMMC) 它从)，然后运行命令“sysupgrade lede-mediatek-32-bananapi,bpi-r2-sysupgrade.tar" 更新内核和 rootfs。
--

- 香蕉派 R2 安装 openWRT: https://www.cnblogs.com/topbin/p/8794152.html
- 香蕉派R2 Openwrt 网口配置分析： https://www.cnblogs.com/topbin/p/9518279.html
- 香蕉派 R2 开发一个简单的路由器 Openwrt : https://www.cnblogs.com/topbin/p/9519881.html
- 香蕉派R2 Openwrt 露西： https://www.cnblogs.com/topbin/p/9519875.html

== 网络配置
网络配置： http://www.fw-web.de/dokuwiki/doku.php?id=en:bpi-r2:network:start

= 高级开发
== GPIO
=== GPIO 控制
```sh
echo xxx > /sys/class/gpio/export
echo in/out > /sys/class/gpio/gpioxxx/direction
echo 0/1 > /sys/class/gpio/gpioxxx/value
```
检查底座 gpio，你可以看到我的是233

R2 gpio 基础.png

例如：如果你想改变 gpio 22 作为高级，你需要输入这样的命令：
```sh
echo 255（22+233） > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio255/direction
echo 1 > /sys/class/gpio/gpio255/value
```
=== PWM 控制
```sh
echo x >/sys/class/pwm/pwmchip0/export
echo 200000 >/sys/class/pwm/pwmchip0/pwmx/period
echo 100000 >/sys/class/pwm/pwmchip0/pwmx/duty_cycle
echo 1 >/sys/class/pwm/pwmchip0/pwmx/enable
```
更多关于 GPIO : http://www.fw-web.de/dokuwiki/doku.php?id=en:bpi-r2:gpio

=== 安装 RPi。GPIO
```sh
git clone https://github.com/BPI-SINOVOIP/RPi.GPIO
cd RPi.GPIO
sudo apt-get update
sudo apt-get install python-dev python3-dev
```
执行“须藤 python setup.py 安装”或“sudo python3 setup.py install”来安装模块

=== 使用 RPi。GPIO
```sh
cd /usr/local/bin
./g40.py
```
测试 RPi。GPIO

== 使用R2开发4G模块
从这里获取更多信息：

link:/en/BPI-4G_module/using_4G_module_with_BananaPi[使用 4G 模块 BananaPi]

== R2 上的 WiFi 和 Ap 模式 Ubuntu
=== 斯塔
```sh
wmt_loader (ignore errors)
stp_uart_launcher -p /etc/firmware &
ip link set wlan0 up
iw dev wlan0 scan | grep SSID
vim /etc/wpasupplicant/wpa_supplicant.conf
```
```sh
network={    
ssid="ssid"    
psk="password"    
priority=1 
}
```
```sh
wpa_supplicant -i wlan0 -c /etc/wpa_supplicant/wpa_supplicant.conf
dhclient wlan0
```

=== AP模式
```sh
wmt_loader (ignore errors)
stp_uart_launcher -p /etc/firmware &
echo A >/dev/wmtWifi
```
创造你的 hostapd.conf: "**维姆 /etc/hostapd/hostapd.conf** "
```sh
interface=ap0
bridge=br0
ssid=test_r2
driver=nl80211
country_code=US
hw_mode=b
channel=1
max_num_sta=5
wpa=2       
auth_algs=1 
rsn_pairwise=CCMP
wpa_key_mgmt=WPA-PSK
wpa_passphrase=ledetest
logger_stdout=-1
logger_stdout_level=2
```
根据您的网络接口(可以上网搜索) 配置 ap0：

我的可以搜索互联网的网络接口是wan，ip是192.168.30.102，所以我配置ap0如下：
```sh
ifconfig ap0 192.168.30.188 netmask 255.255.255.0
```
运行hostapd：“**hostapd -d /etc/hostapd/hostapd.conf**”

配置 dhcp 文件：“**维姆 /etc/dhcp/dhcpd.conf**”
```sh
subnet 192.168.30.0 netmask 255.255.255.0 {
range 192.168.30.2 192.168.30.250;
option domain-name-servers 8.8.8.8;
option routers 192.168.30.1; }
```
配置ap0的dhcp，那么连接ap0的设备就可以获得IP：“dhcpd ap0 -pf /var/run/dhcpd.pid "

- 还有一座桥
- brctl 地址 br0
- brctl 添加 br0 ap0
- brctl addif br wan

配置 br0 ：“ifconfig br0 192.168.30.180 网络掩码 255.255.255.0”

添加 br0 gw 为：“route add -net default netmask 255.255.255.0 gw 192.168.30.1 dev br0”

=== 应用模式 FAQ
如果你遇到这样的问题：

A64 ap 1.png

然后，可以通过以下命令解决：

nmcli 无线电 wifi 关闭

A64 ap 2.png

rfkill 解锁 1

rfkill 解锁 2

ifconfig ap0 up

hostapd -d hostapd.conf

A64 ap 3.png

== R2 上的 WiFi 和 Ap 模式 Openwrt

=== AP模式
. 制作一个 bash 脚本
+
```sh
vim setup.sh
```
+
```sh
#!/bin/ash
wmt_loader &
sheep 3
stp_uart_launcher -p /etc/firmware &
sleep 5
echo A > /dev/wmtWifi &
sleep 5
hostapd -d hostapd.conf
```
. 创建您的 hostapd.conf
+
```sh
vim hostapd.conf
```
+
```sh
interface=ap0
bridge=br-lan
ssid=BPI_R2
driver=nl80211
country_code=CN
hw_mode=g
channel=1
max_num_sta=5
wpa=2
auth_algs=1
rsn_pairwise=CCMP
wpa_key_mgmt=WPA-PSK
wpa_passphrase=ledetest
logger_stdout=-1
logger_stdout_level=2
```
. 让它运行
+
```sh
./setup.sh
```
. 将其添加到开始进度
+
```sh
vim /etc/rc.local
```
+
```sh
 cd /root/
 sleep 6
 ./setup.sh &
```
. 如果你的Ap不稳定，请限速，这里我限制下载速度为 8Mbit/s, 上传为 4Mbit/s

- tc qdisc 添加 dev ap0 根句柄 1：htb 默认 11
- tc 类添加 dev ap0 父级 1:1 classid 1:2 htb 速率 8Mbit ceil 4Mbit prio 2

=== 制作你自己的形象
- 准备一张已经安装好的SD卡 Ubuntu 系统
- 用R2启动你的SD卡，R2启动完成后，复制你的文件并配置你的 Ubuntu，然后关闭R2电源
- 插入您的 SD 卡 Linux个人电脑、“光盘 /media”，然后“ln -s <your account> 圆周率”
- 执行“bpi-migrate -c bpi-r2.conf -c ubuntu-mate-from-sd.conf -d /dev/sdx"
- 那么你现在就可以得到你自己的图像了

== FAQ
香蕉派 BPI-R2 Razberry 板 OpenHab2
https://community.openhab.org/t/banana-pi-bpi-r2-razberry-board-openhab2-help/37222/8

=== TTL电压
调试-uart TTL 耐受 3.3V。

= 参考链接
http://www.fw-web.de/dokuwiki/doku.php?id=en:bpi-r2:start

http://www.banana-pi.org/r2.html

http://forum.banana-pi.org/