= BPI-M8 Introduction

The BPI-M8 is built on the high-performance octa-core AI platform chip A733, which combines a dual-core Arm® Cortex®-A76 and a hexa-core Arm Cortex-A55. It supports an Imagination PowerVR BXM-4-64 MC1 GPU, a 3TOPS NPU, and LPDDR4, LPDDR4x, LPDDR5 DRAM and UFS/eMMC memory.

The BPI-M8 boasts a rich array of peripherals, including USB, DP, UFS, HDMI, MIPI CSI, MIPI DSI, FAN, RTC, and one Gigabit Ethernet port (supporting PoE). It also supports SD card booting and features an onboard KEIIOT K038 WiFi/Bluetooth chip. It is equipped with 4GB of LPDDR5 RAM, 32GB of eMMC storage, and two 12x12mm single-antenna modules.

== Key Features

= Hardware

== Hardware Interface

[options="header",cols="1,3"]
|=====
2+| **HardWare Specification of Banana Pi M8**
| CPU             | Dual-Core Arm Cortex-A76 + Hexa-Core Arm Cortex-A55, up to 2.0GHz
| GPU             | Imagination PowerVR BXM-4-64 MC1
| Memory          | 4GB of LPDDR5 RAM
| Storage         | MicroSD slot,32GB of eMMC storage(Supports UFS modules)
| Network         | 10/100/1000M Ethernet + K038 WiFi/Bluetooth chip
| Video Output(s) | HDMI port output
| Audio Output(s) | 3.5mm headphone jack output
| PCIE            | FPC PCIe socket (reused with DP socket) 
| USB ports       | 4x USB port
| GPIO            | 40 Pin GPIO
| Switches        | PWR button and ADC button
| LED             | Power Status and Activity status
| Power Source    | 5 volt @4A via Micro USB (TYPE C) or PoE support
| Size & Weight   | 
| OS              | 
|=====
