TIP: link:/en/BPI-Bit/Bit_for_MicroPython#_development_tutorialbased_on_microbit[Bit for MicroPython]

= About CodeLab
Codelab.club is a nonprofit organization. official website : https://www.codelab.club/



We are committed to delivering the joy of programming and helping people become creators of the digital age.

Codelab.club is a programming club. Programming is a tool for creation. We will help you get familiar with this tool, but we are more interested in encouraging you to explore and try. We hope to make interesting projects with you, find your passion, find like-minded partners, play and create together.

Codelab.club is a nonprofit, not a company. Codelab.club is free, but free is not the core of our appeal, just as free is not the core of the open source movement (freedom is). Openness, neutrality, sharing and collaboration are our core demands. We hope more volunteers, learners and creators can join us

BPI:bit team works closely with CodeLab to promote STEAM education

= How to use CodeLab scratch3 for bpi:bit
Online link:https://scratch3.codelab.club/[Scratch3 Codelab] website，See here for more details link:https://www.codelab.club/[CodeLab] and link:https://blog.just4fun.site/tag/scratch.html[scratch open soruce documents]

First select the version of the system that works for you and get link:https://adapter.codelab.club/user_guide/install/[adapter] ，No need installation , just open it.

And then going to refer to link:https://adapter.codelab.club/user_guide/usage/#3-microbit[usb_microbit user manual]，in a similar way，choose mpfshell option。