We compiled this Getting Started Guide to help you get started with this
BPI-Centi-S3 development board quickly.

== First Thing

Use a USB-C cable with power and data functions to connect the
BPI-Centi-S3 development board to your computer.

When using it for the first time, its screen will immediately display a
welcome screen after power-on, and the buzzer will beep twice.

BPI-Centi-S3 has been programmed with MicroPython 1.19.1 firmware and
integrated ST7789 C module driver when it leaves the factory. It is
recommended for beginners to use MicroPython to develop and learn.

== Use MicroPython to get started quickly

. See link:./MicroPython/environment.md[Install and configure the
environment], install Python 3, mpremote tool, mpbridge tool, VScode
IDE.
. See link:./MicroPython/VScode_mpbridge.md[How to use VScode + mpbridge
tool] to learn how to connect to the development board, copy, modify,
and delete files on the development board.
. See link:./MicroPython/REPL_use_case.md[REPL Use Case] to quickly
understand the common shortcut keys of MicroPython REPL and the method
of viewing modules.

. After the above three steps, you can start developing.

. For learning Python and MicroPython, we recommend getting started with
Python in the link:https://docs.python.org/3.10/tutorial/index.html[Python
Tutorial]. 
+
Also,try to learn about link:./MicroPython/What_is_MicroPython[What is MicroPython?]

. Apply what you have learned in Python, and look at the
link:https://docs.micropython.org/en/latest/index.html[MicroPython
documentation], you can quickly refer to MicroPython’s special library,
ESP32 port special library for our development.

. Learn some of the differences between the two on the page
link:https://docs.micropython.org/en/latest/genrst/index.html#[Differences
between MicroPython and CPython].

. In the next section of this page, you can find some MicroPython example
that may help you.

. The ST7789 C module driver comes from:
+
link:https://github.com/russhughes/st7789s3_esp_lcd[russhughes/st7789s3_esp_lcd],
The MIT License
+
In this GitHub repository, you can check all the methods of the st7789
module, as well as the compiled methods, thanks to russhughes for his
open source contributions.

. If you have an unexpected vicious BUG during development that prevents
the development board from starting normally, or other reasons cause the
firmware to be erased or damaged, see
link:./MicroPython/Burn_firmware.md[Burn firmware].

=== MicroPython example
. link:./MicroPython/lcd_init[LCD init]
. link:./MicroPython/Display_jpg_images[Display jpg images]
. link:./MicroPython/Display_text[Display text characters]
. link:./MicroPython/Make_semi-transparent_rectangular_text_box[Make semi-transparent rectangular text box]
. link:./MicroPython/Refres_textbox_on_jpg[Refresh textbox on jpg]
. link:./MicroPython/Display_multiple_vector_fonts[Display multiple vector fonts]

== Use Arduino to get started quickly


