TIP: link:../GettingStarted_BPI-Centi-S3[返回 BPI-Centi-S3 入门指南]

BPI-Centi-S3 出厂已烧录带 ST7789
并口驱动的 MicroPython 固件，通常可跳过本步骤。

如果开发过程中遇到严重错误，导致
开发板无法正常启动，或因其他原因造成
固件被擦除或损坏，可从下面的 GitHub 链接获取
已编译的固件并自行烧录。

NOTE: link:https://github.com/BPI-STEAM/BPI-Centi-S3-Doc/tree/main/micropython_st7789s3_firmware[GitHub: BPI-Centi-S3 micropython 固件]

== 固件信息

. micropython1.19.1_esp32s3_qspram_st7789s3.bin
* MicroPython 1.19.1 发布版
* ESP32-S3、Quad SPIRAM、8 MB Flash
* russhughes/st7789s3_esp_lcd
. micropython1.20.0dev_esp32s3_qspram_st7789s3.bin
* MicroPython 1.20.0 主分支开发版（截至 2023 年 6 月 6 日，支持 mip、espnow）
* ESP32-S3、Quad SPIRAM、8 MB Flash
* russhughes/st7789s3_esp_lcd

=== 设置固件下载模式

操作方法有两种：

. 通过 USB 将开发板连接到计算机，按住 BOOT 按钮，然后
按下并松开 RESET 按钮，最后松开 BOOT
按钮。
. 在开发板断电状态下按住 BOOT 按钮，
再通过 USB 将其连接到计算机，最后松开 BOOT
按钮。

芯片会在复位或重新上电时，
通过 BOOT 按钮控制的 GPIO0 选择启动模式。

在设备管理器中确认 COM 端口。
固件下载模式和正常模式使用的 COM 端口号
通常不同。

=== 安装 esptool 工具
> 需要先安装 Python 3，参见 link:./environment#_install_the_python_environment[安装 Python 环境]。

在终端中输入以下命令来安装 esptool。

```
pip install esptool
```

=== esptool 命令


IMPORTANT: 对 Flash 的所有操作都不可逆，请注意备份
有价值的数据。


* 擦除闪存

```
python -m esptool --chip esp32s3 --port COM1 --baud 460800 erase_flash
```

* 写入 Flash

```
python -m esptool --chip esp32s3 --port COM1 --baud 460800 --before=usb_reset --after=no_reset write_flash 0x0 micropython1.19.1_esp32s3_qspram_st7789s3.bin
```
