= Allwinner A40i for Industrial control gateway design

Industrial control gateway 1.jpg

More about this project ,please see :

Awinner A40I for Industrial control gateway design

= Realtek RTD1296 Intelligent voice, video processing platform
RTD 1296 design 1.JPG

RTD 1296 design case.jpg

More about this project ,please see :

Realtek RTD1296 Intelligent voice, video processing platform

= MediaTek MT7622 5G + 4G LTE+Wifi AC+Gigabit Multiplex aggregate route
BPI-R64 4g 1.JPG

5G gateway 2.jpg

. MediaTek MT7622,1.35GHZ 64 bit dual-core ARM Cortex-A53
. (1-2)G DDR and 8G eMMC flash
. 1x5G port , Use USB 3.0 or PCIe bus.
. 4x4G LTE , support OpenMPTCProuter Multiple polymerization protocol.
. 5xGigabit port. support VPN ,router function.
. wifi 802.11 b/g/n/ac function support.
. IoT expanding application
. Base on Banana Pi BPI-R64 hardware design

Moere,please see here:

link:https://docs.banana-pi.org/en/BPI-MNF/BananPI_CPI-MNF[5G + 4G LTE+Wifi AC+Gigabit Multiplex aggregate route]

Discuss on forum : http://forum.banana-pi.org/t/bpi-4-0-bpi-r64-for-5g-4g-lte-wifi-ac-gigabit-for-converged-communication-gateway/9555

= ESP32 Sweet fume machine Intelligent sleep meter
Sweet fume machine 4.jpg

Use ESP32 design , suppor WiFi and BT to connect network.

More Spec ,please see :

= 4G LTE router design
Banana pi 4g router 1.jpg

More Spec,please see : http://forum.banana-pi.org/t/bpi-4-0-4g-lte-router-design/9277

= DOJO smart home
Dogo.png

Dojo official webstie: https://dojo.bullguard.com/

= Magic mirror
Magic mirror 2.JPG

PCBA base on BPI-M3 with allwinner A83T chip design

Magic mirror 1.jpg

Forum discuss: http://forum.banana-pi.org/t/banana-pi-bpi-4-0-oem-odm-project-magic-mirror-base-bpi-m3-allwinner-a83t-chip-design/7410

= 4G Multi-network fusion server
This is base on BPI-R2, with 4 4G module desin. We can work with our customers to provide overall solutions

== 4G Multi-network fusion server

4G Multiple 2.jpg

Chassis design file : https://drive.google.com/file/d/1C9LuXVgexsUN3K8DqApFNG4FLpwn54Ms/view?usp=sharing

== 4G Multi-network fusion terminal

4G Multiple 1.jpg

product website: https://www.aixiaocao.com/

== OpenMPTCProuter
NOTE: 2018-10-12 update, OpenMPTCProuter use MultiPath TCP (MPTCP) to aggregate multiple Internet connections and OpenWrt. and have official support BPI-R2.

Image download: https://www.openmptcprouter.com/download

Source code on github: https://github.com/Ysurac/openmptcprouter

Forum pthread: http://forum.banana-pi.org/t/banana-pi-bpi-r2-new-image-openmptcprouter-official-support/7229

= MultiQB Home multimedia gateway
What we do : hardware design, BSP software design, tooling design, quantity production, product certification

MultiQB front.jpg

Pcba inside:

P图 - 副本.jpg

Case design:

QQ图片20151112174344.png

== Hardware Specs

- SIZE: two-deck, 88x88 mm
- CPU Chipset: A20 ARM Cortex™-A7 Dual-Core 1 GHz
- GPU Chipset: ARM Mali400MP2Complies with OpenGL ES 2.0/1.1
- Memory: 1 GB DDR3
- Storage Slot: micro SD Card 16G Bytes
- Network Ethernet: – 10/100/1000Mbps WAN x 1 – 10/100/1000Mbps LAN x 4
- WIFI: – 3x 2.4GHz, Support IEEE 802.11b/g/n，Up to 300Mbps – 1x 5GHz，Support IEEE 802.11a/n/ac，Up to 433Mbps – External High-Gain Antenna 2.4GHz x3，5GHz x1 –WIFI model MT7632 or AP6335
- 4G LTE – SimCom Sim7100C, FDD B3 LTE 1800, – Model SIM7100C – External High-Gain Antenna 4G x1
- USB: USB Host 2.0 x 1
- CAMERA: Camera x 1, Screen resolution HD 1280x720 pixels, 30 FPS, UVC H.264 encoding technology, CSI Connector
- AUDIO Input: Microphone x 1
- VIDEO Outputs: HDMI out x 1
- AUDIO Outputs: 3.5mm Jack and HDMI
- SPEAKER: BP-5032-44, 1xSpeaker, Diameter 50mm, Depth 32mm, Power 4w, Impedance 4±15%Ω
- KEY: POWER KEY x 1 Touch Sensor Power Button RESET KEY x 1
- LED: RJ45 LED (Upload, Download) x 5 WIFI LED (2.4G, 5.8G) x 2 POWER STATUS LED x 1 GPIO LED (4 pins LED) x 1 USB LED x 1 CAMERA LED x 1 4G LED x 1 AUDIO LED x1 MICROPHONE LED x1
- Debugging: Serial Console, JTAG
- Reserved Pin: GPIO PIN x 26, UART, 12C bus, SPI bus with two chip selects, CAN bus, ADC, PWM, +5V, +3.3V, GND
- IR Receiver: x1
- Power Source: Micro-USB Power DC 5V/2A
- Battery: Li-ION 4400 mAh 3.7V, Battery Connector: x1
- Adaptor: DC Adaptor 5V/2A with micro-USB cable
- Easy to add zigbee, z-wave ,NB-IoT and other IoT function.

= KANO Pixel Kit
What we do : hardware design, quantity production

KANO 1.jpg

This product is for STEAM education with KANO scratch app:

Blockly web.jpg

The link:https://kano.me/store/uk/products/pixel-kit[Kano Pixel Kit] is a fun build-it-yourself, programme-it-yourself digital display, aimed at youngsters who are just getting interested in coding and playing with technology.

https://www.youtube.com/watch?v=-Gs5UuEjYgI&list=PLGddqVjX_E2EGskc9rP9eEf7tJ8K-V0du

https://www.youtube.com/watch?v=As4HTgXgyPY

http://upflow.co/l/LHkO/2017/08/kano-pixel-kit-review.html

= eBlocker
What we do : hardware design, BSP software design, PCBA support, product certification

NEW eBlocker Family Shop money back.png

eBlocker works as effectively as it does easily: unpack it, plug it in, ready. Without additional software installation and configuration. All you need is a free Ethernet port in your home network and off you go.

eBlocker official website : https://www.eblocker.com/en/

Video demo:https://www.eblocker.com/wp-content/uploads/2016/02/whatiseblocker-1280x720.mp4

Image download link:https://www.eblocker.com/en/download/

= 3G Information security terminal
What we do ： hardware design, BSP software design, tooling design, quantity production, product certification

IMG 3036.JPG

PCBA inside:

A20 for 4G.JPG

= 4G Industrial safety tablets
What we do : hardware design, BSP software design, tooling design, quantity production, product certification

IMG 3085.JPG

PCBA inside:

A20 for 4G mid.JPG

= MTK MT6737 4G watch
hardware design, All software design, tooling design, quantity production, product certification

4G watch 1.JPG

MTK MT6737 4G watch UI, we do can customization.

4G watch 6.JPG

Use MTK MT6737 design 4G watch project for China Mobile.This product has passed the certification of China mobile.

4G watch PCBA:

4g watch pcba.jpg

4G watch PCBA with shielding case:

4g watch pcba 1.jpg

4G watch Spec

System Physical Standard Configuration:

4g watch spec 1.png

System hardware configuration:

4g watch spec 2.png

Interface Configuration:

4G watch spec 3.png

Software Configuration：

4G watch spec 4.png

Necessary Accessories：

4G watch spec 5.png