TIP: link:../GettingStarted_BPI-Leaf-S3[返回 BPI-Leaf-S3 入门指南]


== 外部硬件要求

一个电位器。

== ESP32-S3 ADC

ESP32-S3 芯片集成两个 **ADC 模数转换器**，测量范围为 0～3100 mV，分辨率为 12 位，即将该范围划分为 2^12=4096 个数字量级。

两个 ADC 各有 10 个测量通道：ADC1 对应 GPIO1～10，ADC2 对应 GPIO11～20。

== 连接方式

GND 接 GND，VCC 接 3V3，S 输出端接 GPIO11，使用 ADC2 的通道 1 测量。

GPIO1~20个引脚可用作 ADC 输入引脚。

== 代码

```py
from machine import Pin,ADC
import time
adc11 = ADC(Pin(11),atten=ADC.ATTN_11DB)
#adc11 = ADC(Pin(11))
#adc11.atten(ADC.ATTN_11DB)
while True:
     read=adc11.read()
     read_u16 = adc11.read_u16()
     read_uv = adc11.read_uv()
     print("read={0},read_u16={1},read_uv={2}".format(read,read_u16,read_uv))
     time. sleep_ms(100)
```

[options="header"]
|===================================================
| 衰减值 | 可测量输入电压范围
| ADC.ATTN_0DB      | 0 mV～950 mV                 
| ADC.ATTN_2_5DB    | 0 mV～1250 mV                
| ADC.ATTN_6DB      | 0 mV～1750 mV                
| ADC.ATTN_11DB     | 0 mV～3100 mV                
|===================================================


  1. `ADC(*, atten)` 初始化 ADC 的通道 GPIO 引脚，您可以选择使用 `atten` 设置衰减值，控制芯片可测量的输入电压范围。如果不设置，则为默认值 `atten=ADC.ATTN_0DB` 或上次设置的值。
  2. 初始化 ADC 通道后，可通过 `ADC.atten()` 修改衰减值。
  3. `ADC.read()` 读取 ADC 并返回结果；ESP32-S3 的 ADC 返回 12 位精度数据。
  4. `ADC.read_u16()` 读取 ADC 并返回 16 位数据。
  5. `ADC.read_uv()` 根据 ADC 特性返回校准后的输入电压，单位为 `uV`（微伏）。返回值的实际分辨率为 `mV`（毫伏），即始终为 1000 微伏的整数倍。

Wi-Fi 功能也使用 ADC2，因此启用 Wi-Fi 时，从 ADC2 的 GPIO11～20 通道读取模拟值会引发异常。

建议使用 `ADC.read_uv()` 读取电压。该值根据 ADC 特性校准，比另外两种读取方法更准确。使用 `ADC.read_uv()//1000` 可直接获得 `mV`（毫伏）分辨率的数据。

直接打印 `ADC.read()` 或 `ADC.read_u16()` 可获得十进制值；可用 `hex()` 转为十六进制，例如 `hex(ADC.read() )`，也可用 `bin()` 转为二进制。
