= Getting Started

== Development environment setup

1、**First, install a comfortable editor.**

Open Terminal and update your system software list, then update Vim.
```
sudo apt update
sudo apt install vim
```

2、**Changing Software Sources**

If you are unable to access or experience slow access to the default Ubuntu software source, please switch to another software park.(Before making changes, it is best to use the **cp** command to back up the original Ubuntu source to prevent modification errors.)
```
cd /etc/apt
sudo vim sources.list
```
Press the "**I**" key to enter the editing state, and then replace the source you want to change.
(The following use cases use the Tsinghua University source in China.)
```
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal main restricted
universe multiverse
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal-updates main
restricted universe multiverse
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal-backports main
restricted universe multiverse
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal-security main
restricted universe multiverse
```
After replacement, press the "**ESC**" key and enter "**:wq**" to exit.

3、**Installing the necessary tools: From Git to Docker**

Install git
```
sudo apt update # I just changed the repository, remember to update again
sudo apt install git x11-xserver-utils udev
```

Install Docker(Use Tsinghua source image to accelerate)
```
# Add the Docker key
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
# Configure the Tsinghua Docker image
echo "deb [arch=$(dpkg --print-architecture) signed-￾by=/usr/share/keyrings/docker-archive-keyring.gpg] https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/ubuntu plucky stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
# Install Docker core components
sudo apt update
sudo apt install docker-ce docker-ce-cli containerd.io
```