= BPI-WiFi6 Router Introduction

Banana Pi BPI-Wifi5 Router use Siflower SF19A2890S and AN8855R Gigabit switch chip design. the  It is a high performance wireless router for small and micro businesses, homes and other networking environments. 

BPI-Wifi5 Router dual-band wireless router, 2.4G 2T2R, 5.8G 2T2R coexist at the same time. The use of four omnidirectional high-gain antennas, with strong signal penetration and wider coverage, which makes the already strong signal more powerful, data transmission is also smoother. MU-MIMO multi-device transceiver technology has low latency and multiple devices are stably connected simultaneously, thus ensuring a good experience for multiple devices.

BPI-Wifi5 Router adopts the national silicon Chang chip SF19A2890S +AN8855R (Gigabit switch chip) solution, providing gigabit network interface, 1 gigabit WAN port and 3 gigabit LAN ports, supporting 2.4G and 5G, wireless transmission rate of 1200Mbps; Supports rich software features, providing the ideal high-performance product for small and micro businesses and families.
 



