== Overview

Banana Pi BPI-RV2 open source gateway is a device based on  Siflowe SF2H8898 SoC, 1 × 2.5G WAN network interface, 5 Gigabit LAN network interface, onboard 512MB DDR3 memory, 128 MiB NAND, 16 MiB NOR, M.2 interface, MINI PCIE and USB 2.0 interface, etc.

Banana Pi BPI-RV2 open source gateway is a collaboration between Silicon Chang and Banana Pi open source community (Banana Pi)

== SF2H8898 chip Brief

SF21H8898 is a high-performance industrial SOC gateway chip developed by Siecong Communication. The CPU adopts RISC-V architecture (quad-core processor, main frequency 1.4Ghz), built-in self-developed NPU network processor (supports L2/L3 hardware processing, IPv4/IPv6 dual stack, 20Gbps switching capacity, and supports the following functions: The network side supports QSGMII, SGMII/HSGMII, and RGMII interfaces, and supports the IEEE 1588 PTP function for time synchronization. Supports external DDR3/DDR3L/DDR4 SDRAM and NAND/NOR SPI Flash. High-speed interface has USB2.0, PCIE2.0, low-speed interface has SPI, UART, I2C, PWM and so on. Can be used as enterprise gateway, industrial control host.


== Key Features 
* Siflowe SF2H8898 4 core RISC-V processor
* With Siflowe NPU, enterprise-class gateway level data forwarding processing capability can be achieved.
* 512MB DDR3 RAM 
* 1 x 2.5GbE network and 5 x giga port
* 128 MB SPI NAND and 16 MB SPI NOR flash Ensure that the onboard system is indestructible，
* M.2 2242/2230 interface support NVMe SSD (PCIe gen 2 x1)
* RTC 
* PoE Network power support


== Getting started

TIP: link:/en/BPI-RV2/GettingStarted_BPI-RV2[BPI-RV2 gateway board Getting started]

= Hardware 

== Hardware interface

== Hardware spec

[options="header",cols="2,6",width="70%"]
|=====
|item |introduce
|SoC |Siflowe SF2H8898 4 core RISC-V @ 1.25GHz
|RAM |512MB DDR3
.3+|Storage|128 MB SPI NAND Flash is used in U-boot and Linux systems
|16 MB SPI NOR flash，For U-boot and Linux systems, write protected by default (refresh can be enabled by jumper)
|M.2 2242 interface  support NVMe SSD hardsik(PCIe gen 2 x1)
.2+|Network |1 x 2.5GbE RJ45 port
|5 x giga RJ45 port
.2+|USB |Use the USB Type-C (device, console) port of the UART to USB chip
|1x USB 2.0 Type-A USB HOST port
.2+|PCIE |M2 keyB， Supported Rates PCIe gen 2 x1，Can be used to connect SSD hard drives, 5G modules, etc
|MINI PCIE，Supported Rates PCIe gen 2 x1，Can be used to connect WiFi module, wired network card, etc
|Extension| MikroBUS expansion module socket
|Debug| Console connected via USB-C port or 3-pin connector
|RTC| Support for on-board RTC real-time clock
.4+|Others |Reset and user buttons
|Boot choose：NAND（normal） Or NOR（Reset）
|(I2C interface) RTC，Backup battery holder with CR1220 button battery
|support add  802.3at/af PoE module
|Size| 148 x 100.5 mm
|=====

= 开发

== 软件源代码

== 参考资料

= 系统镜像

= 快速购买

