= OpenWRT One Introduction

The “OpenWrt One/AP-24.XY” router board based on MediaTek MT7981B (Filogic 810) SoC and MediaTek MT7976C dual-band WiFi 6 chipset.

OpenWrt One is a device based on the MediaTek Filogic 810 SoC that has WiFi 6, dual-band, 3×3/2×2, 1 x 2.5Gbit WAN, 1 x 1Gbit LAN, 1GB DDR4 RAM, 128 MiB NAND, 16 MiB NOR, M.2 SSD and USB 2.0.

OpenWRT one is the first board design with OpenWRT opensource communtity.and designed in collaboration with Banana Pi that will also handle manufacturing and distribution of the router board. The OpenWrt One/AP-24.XY router should provide a source of income for the project, for example, to cover the cost of hosting and OpenWrt conferences, with Banana Pi selling the board through their distribution network, and for every device sold, donating to the Software Freedom Conservancy (SDC) with the funds earmarked for OpenWrt.

== MediaTek MT7981B(Filogic 810)


== Key Features


== Application direction



= Hardware 

== Hardware inerfact 


== Hardware spec



== OpenWRT One photo

= Software

== OpenWRT communtity official support