== BPI-3A5000 Mini PC

BPI-3A5000 is a Mini PC developed by Banana Pi open source community Loongson 3th-generation 3A5000 processor + Loongson 7A1000 bridge chip.

BPI-3A6000 can be applied to enterprise office, personal minicomputs, high-performance industrial computer, as well as education, medical, finance, edge computing and other fields. It has the advantages of high performance computing, portability, low energy consumption and easy management. The Loongson BPI-3A6000 MINIPC supports two DDR4 SODIMM slots, the memory rate is 3200M, a single memory supports 8GB/16GB/32GB, and the maximum memory capacity is 16GB. Storage Supports one M.2 2280-size NVME SSD slot and one 2.5-inch SATA disk expansion.

BPI-3A6000 Longson minicomputeruses mini case design, unique high density heat dissipation structure design, high performance, high density and high reliability in one; It is easy to move and saves space when it meets various application scenarios.

== Application scenarios

In addition to conventional computing applications, the BPI-3A5000 can also be pre-installed with the following industrial control applications, including but not limited to:

* 300+ Industry general/industry specific protocol library
* Video access transmission/control/recording/linkage function
* Computational programming capabilities
* Industrial firewall function
* Soft PLC programming function
* C/S architecture SCADA system functions
* B/S architecture SCADA system functions

== Product feature

* Mini size 
** The volume of the whole machine is less than 1L, which is 40 times smaller than the desktop
** Small size, easy to carry, easy to organize, one hand
** Can support wall hanging, can be hung behind the monitor/TV series, save desktop space
* High performance
** Using the fourth generation of Loongson 3A5000 CPU+7A1000 bridge
** Supports two DDR4 SODIMM slots
** Supports memory rates up to 3200Mbps
** Supports multiple CPU cores, up to 4 physical cores and 8 logical cores
* High reliability
** Advanced memory fault-tolerant ECC function (currently not supported by existing BIOS)
** The use of all copper fin cooling architecture, so that the CPU performance is fully developed, full load performance is still reliable
** Support intelligent speed adjustment function, the fan speed dynamically adjusts with the system temperature, effectively reducing the system noise and power consumption
* Interface rich
** Multiple interface types, can meet the needs of multiple scenarios at the same time
** Dual display interface to achieve dual HDMI + VGA output at the same time, create a multi-screen working environment, improve efficiency and entertainment experience
** NVMe and SATA interface dual hard disk design, easy to expand, increase storage space

== getting started


