== BPI-RT2 介绍

BPI-RT2 WiFi 6 路由器采用了 Realtek RTL8198D 设计。它是一款高性能无线路由器，适用于小型和微型企业、家庭及其他网络环境。

BPI-RT2路由器双频无线路由器、2.4G 2T2R、5G 2T2R可以同时存在。采用四根全向高增益天线，信号穿透力强，覆盖范围更广，使本已强信号更强大，数据传输也更加顺畅。MU-MIMO多设备收发技术延迟低，多个设备能稳定同时连接，从而确保多设备良好的使用体验。

== 瑞昱 RTL8189D芯片

瑞昱是一款高度集成的片上系统（SoC），专为高性能网络设备设计。它集成了双核CPU、硬件交换引擎、多端口千兆以太网PHY收发器以及全面的网络协议处理加速功能，是构建企业级网关、智能路由器和网络交换设备的理想核心解决方案。 该RTL8198D集成了四个千兆以太网物理层收发器，分别用于10Base-T、100Base-TX和1000Base-TX，以及两个HSGMII接口，用于与外部物理接互。

== 主要特点
* RTL8198D 双核 MIPS interAptivTM CPU
* 256MB DDR3（与RTL8198D内嵌）
* 128MB SPI-NAND 闪存
* 1 x 1 G RJ45 WAN
* 3 x 1 G RJ45 局域网
* 1x UART 调试
* 1 个 USB 3.0 插槽

== 应用方向
* 千兆企业网关
* VPN路由器
* 智能WiFi AP
* 网络交换设备
* 集成访问设备
* 其他嵌入式系统则需要高性能告罗处理和VoIP功能

== 快速上手使用
TIP: link:https://docs.banana-pi.org/en/BPI-RT2/GettingStarted_BPI-RT2[Getting Started BPI-RT2]

= 硬件
== 硬件接口示意图

== BPI-RT2 产品图集
link:/en/BPI-RT2/Photo_BPI-RT2[Banana Pi BPI-RT2 Product photo gallery]

== 硬件规格
|====
2+|  ** BPI-RT2硬件规格 **
| CPU主控          | RTL8198D 双核MIPS interAptivTM CPU
| SDRAM内存          | 256MB DDR3（与RTL8198D内嵌）
| 板载存储 | 128MB SPI-NAND 闪存
| 板载网口 | 	4端口 10/100/1000Mbps 以太网
| Wifi 无线         | 支持RTL8832和RTL8192 Wifi6 

| USB接口              | 1x USB 3.0 TypeA
| 按键        | 重置按钮，WPS键启动开关
| Led指示灯             |重置按钮，WPS键，启动开关
| DC 供电        | 12V/1A 
| 尺寸          | 97mm x 65mm
| 重量          | 250g 
|====

= 配件
= 开发
==  软件代码
TIP: BPI-RT2 OpenWRT 22.03 BSP on Github: https://github.com/BPI-SINOVOIP/BPI-RT2/

== Resources
TIP: BPI-RT2 原理图

百度网盘： https://pan.baidu.com/s/1Wd4yxy1mUXu1eSa3Pi-yMw?pwd=8888

Google硬盘: 
https://drive.google.com/file/d/1t1pO8gN1v9Q2bq5pGJ9on1ZpqPjUqGAE/view?usp=sharing

TIP: BPI-RT2 DXF 文档

百度网盘： https://pan.baidu.com/s/1CKIfFioLkRqG26FEJBSLYA?pwd=8888 

Google硬盘： 
https://drive.google.com/file/d/11G-rkszFZTKMLRdHuoz0WHshGo_mjhWF/view?usp=sharing
